### ISSUE TITLE
Epitweetr downloading of dependencies in the Shiney App stuck on "Pending" Status

### ISSUE THREAD

**Issue by venomjackal** [EU-ECDC/episomer#73]
Hi All,

I am hoping someone here can assist with having issues trying to get past the downloading of dependencies in the Shiney App.

They are just stuck saying pending and I cannot start the epitweetr database as per the screenshot:
![Config](https://user-images.githubusercontent.com/100995701/181798754-8fd21ad1-e846-4f7e-adc9-a4cfddacdb87.png)

I have carried out the following steps to install and configure epitweetr:

- Using Windows 10 Enterprise machine version 21H2
- Install the latest version of R-4.2.1 for Windows
- Microsoft Visual C++ 2013 Redistributable (x64 is already installed)

Run 64 bit version of R as administrator

Check the Java directory (Java SE Development kit 18.0.2 64bit is installed)
> Sys.getenv("JAVA_HOME")
 "C:\\Program Files\\Java\\jdk-18.0.2"

Install the following using CRAN repository ( R> Install packages) 
	• UK Mirror London 1 Mirror
	• Select epitweetr (downloads and installs w/o errors)
	• Select  taskScheduleR (downloads and installs w/o errors)
	• Select rtweet (downloads and installs w/o errors)
	• Select TinyTex (downloads and installs w/o errors)

Double checked these are installed by running "Installed.packages ()" and I can see them all installed

In R console I run epitweetr & Shiney App

library(epitweetr)
epitweetr_app("data_dir")

This created folder in my user profile area C:\Users\%username%\Documents\data_dir . It has the following files (fs.PID, fs_mon.PID, and properties.json)

The command opens Shiney App in Firefox (Tried in Edge as the well same issue)

Go to Configuration can see the following URL's

GeoNames URL	http://download.geonames.org/export/dump/allCountries.zip
Maven repository	https://repo1.maven.org/maven2
Winutils URL	https://github.com/steveloughran/winutils/raw/master/hadoop-3.0.0/bin/winutils.exe

Troubleshoot option > Diagnostics > run diagnostics returns error 
"Warning: Error in get_token: Cannot get a token. Please create it from the configuration page"

Try and activate the database from GUI nothing happens

I can see the task scheduler has created the following:

- Epitweetr_fs_loop
- Epitweetr_search_loop
- Spitweetr_detect_loop

If I try and manually run the database activation in R Console I get the following error:

 library(epitweetr)
fs_loop("data_dir")
                                                       
Launching fs
Exception in thread "main" java.lang.NoClassDefFoundError: scala/collection/Seq
        at org.ecdc.twitter.Tweets.main(Tweets.scala)
Caused by: java.lang.ClassNotFoundException: scala.collection.Seq
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 1 more
The epitweetr Scala API was stopped with the following error
Error in spark_job(paste("fsService", "epiHome", conf$data_dir)): Error encountered while exeuting:  

"C:\Program Files\Java\jdk-18.0.2\bin\java" -cp "C:/Program Files/R/R-4.2.1/library/epitweetr/java/ecdc-twitter-bundle_2.12-1.0.jar;data_dir/jars/*" -Xmx4g  org.ecdc.twitter.Tweets fsService epiHome data_dir

It seems to me for some reason the dependencies are not downloading.

**Comment by forchard** [comment]
Hi @venomjackal 
Welcome to the epitweetr community!
Sorry for not being able to answering before I hope it is not too late!

I think the issue you have it is because you are using a relative path on the data dir.

This has been confusing in the past for other users. You need to use the full path "c:/Users/....") when running epitweetr. @lauespinosa maybe we should try to detect if the path is relative and throw an error.

You will need to retry the activation of the loops too.

Please let me know if this helps.

Best Francisco

**Comment by lauespinosa** [comment]
Closing this issue due to inactivity
